<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge">';
echo '<title>homework</title>';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-3">';
echo '<img src="https://thestandard.co/wp-content/uploads/2018/12/from-meme-to-3d-meme-12.jpg" class="img-fluid">';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="row">';
echo '<img src="https://i.pinimg.com/originals/b8/15/49/b815495efe8926a2575fd4a65cb6f8cd.jpg" class="img-fluid"/>';
echo '</div>';
echo '<div class="row">';
echo '<img src="https://i.pinimg.com/736x/8a/09/d5/8a09d5533f29ff05b93df1d18c1967a0.jpg" class="img-fluid"/>';
echo '</div>';
echo '<div class="row">';
echo '<img src="https://i.pinimg.com/564x/16/b7/1e/16b71e06b000ec95d591c091a77221b2.jpg" class="img-fluid"/>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="row">';
echo '<img src="https://pbs.twimg.com/media/D3WBSONU0AAoZV3.jpg" class="img-fluid"/>';
echo '</div>';
echo '<div class="row">';
echo '<img src="https://i.pinimg.com/736x/8a/09/d5/8a09d5533f29ff05b93df1d18c1967a0.jpg" class="img-fluid"/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>
